### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by atsushi59** [atsushi59/Where-do-you-take-your-kids#142]
## 各種情報
サービス名　こどもとどこいく？
サービスURL　https://where-do-you-take-your-kids.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] Geolocation API、Geocoding APIを使用して位置情報（住所）を取得
- [x] GPT-4 APIを使用して選択ボタンからの検索結果を表示
- [x] Directions API、NAVITIME Route(totalnavi)APIを使用しユーザーが選択した時間内に行ける場所のみ表示する
- [x] Places APIを用いて名前、住所、営業時間、公式HPの表示且つDirections API、NAVITIME Route(totalnavi)APIから取得した所要時間の表示
- [x] 検索結果からGoogle Mapsに移動し、ナビゲーションまたは乗換案内ページを表示する

## READMEレビュー時から変更した機能

- [x] 1日辺りの検索回数の上限設定

**Comment by tarakish** [comment]
> 1日辺りの検索回数の上限設定

こちら一度の検索で`本日の検索上限を超えました`と表示されました。予期せず複数回リクエストを送るようになっていないか一度ご確認をお願いします。

**Comment by atsushi59** [comment]
回答ありがとうございます

ご指摘の内容を修正しました

ご確認の程よろしくお願い致します

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
